### PR TITLE
Update paper ref after JMLR acceptance

### PR DESCRIPTION
**Pull request by bellet**
This updates the reference to the metric-learn paper in the README and the doc, following acceptance to JMLR

### CODE REVIEW

**Comment by bellet** [comment]
@wdevazelhes could you please update the doc branch after merging this so that the change is immediately reflected in the doc website? Thanks!

**Comment by bellet** [comment]
The failing test is unrelated to this PR - but it was documented in #264. We should fix this separately

**Comment by wdevazelhes** [comment]
> @wdevazelhes could you please update the doc branch after merging this so that the change is immediately reflected in the doc website? Thanks!

Sure, will do!

**Comment by bellet** [comment]
Thanks!

**Comment by wdevazelhes** [comment]
done :)

**Pull request merged**
