### PR TITLE
[MRG] Rename repo addresses

### PR DESCRIPTION
**Pull request by wdevazelhes**
This renames all `metric-learn/metric-learn` into `scikit-learn-contrib/metric-learn`

### CODE REVIEW

**Comment by bellet** [comment]
Great, merging! I think we are done with the repo move modifications now

**Comment by terrytangyuan** [comment]
Though it doesn’t look like the changes are reflected on the website since gh-pages branch is not updated.

**Comment by bellet** [comment]
Indeed, @wdevazelhes can you take care of it? I am not familiar with this

**Comment by wdevazelhes** [comment]
> Indeed, @wdevazelhes can you take care of it? I am not familiar with this

Sure, done. Right now we need, on the `gh-pages` branch, to delete everything except the `.git` and the `.nojekyll` (which I don't know what it's for), and to paste there the content of the `_build/html/*` resulting from running `cd doc; make html` on the master branch.
Maybe this could be automated though

**Comment by bellet** [comment]
Thanks!

**Comment by perimosocordiae** [comment]
The `.nojekyll` file tells the Github Pages serving software to treat everything as plain files: https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/

**Pull request merged**
